### ISSUE TITLE
(Java) IP Ban makes SteamCondenser Source RCON go boom

### ISSUE THREAD

**Issue by comanoodle** [koraktor/steam-condenser#14]
From the newsgroup:

So, I wrote an IRC PUG bot. It manages the PUGs on its own, no need
for admins on the most part.

So anyway, I made a typo in one of the RCON passwords. The bot checks
all servers every 60 seconds, checks if there's a match in progress,
and if not, removes the passwords.

That + typo = the bot eventually got IP banned by that server.
Whenever that password removal thread hit the server it was banned on,
I got this exception:
Exception in thread "Thread-0" java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Unknown Source)
        at steamcondenser.steam.sockets.SteamSocket.receivePacket (SteamSocket.java:103)
        at steamcondenser.steam.sockets.RCONSocket.getReply(RCONSocket.java:48)
        at steamcondenser.steam.servers.SourceServer.rconAuth(SourceServer.java:57)
        at coma.ntpugbot.ntRcon.exec(ntRcon.java:33)
        at coma.ntpugbot.Server.isPassworded(Server.java:98)
        at coma.ntpugbot.Server.matchInProgress(Server.java:110)
        at coma.ntpugbot.Server.clearPassword(Server.java:55)
        at coma.ntpugbot.ClearPasswords.run(ClearPasswords.java:18)

Since it's an illegal argument exception, it can't be coming from my
code. My code does vary the contents of the arguments, but the type
can never change.

**Comment by koraktor** [comment]
This has been fixed in e166793fb96cb3fc08b9d984036015a7f8135f02.
