### ISSUE TITLE
Help with TF2Inventory

### ISSUE THREAD

**Issue by itsfocus** [koraktor/steam-condenser#179]
Sorry if this isn't the correct place to put this, but I really don't know where else to get help for this.
Now this is probably an easy fix, as I'm new to Java (and programming). I can't seem to create a TF2Inventory. This is my code so far:

```
public static void main(String[] args) throws SteamCondenserException, WebApiException {
    long vidya = 76561198000641523L;
    SteamId id = SteamId.create(vidya);
    //System.out.println(id.getCustomUrl());
    TF2Inventory inv = TF2Inventory.create(vidya);
    inv.getItems();
    System.out.println(inv);
}
```

This is the output I'm getting:
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
    at backpack.Backpack.main(Backpack.java:18)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 1 more
Java Result: 1

I've done some Googling and it seems I'm missing a .jar file, but I can't seem to figure out which one. I've already added json-lib-2.4-jdk15.jar and that didn't change anything.

**Comment by koraktor** [comment]
Steam Condenser depends on the library from json.org, you can get the JAR [here](http://search.maven.org/#artifactdetails%7Corg.json%7Cjson%7C20090211%7Cjar) (bottom of the page) if you don't use a build tool like Maven.

BTW for questions like this there's a [Google Group](http://groups.google.com/group/steam-condenser).
