### ISSUE TITLE
Getting a 503 error

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#183]
Whenever I try to do anything with this, I always get a 503 error. This is my code:
'''java
try {
            WebApi.setApiKey(API_KEY);
            SteamId id = SteamId.create("market03");
            System.out.println(isF2P(id));
        } catch (SteamCondenserException | IOException
                | ParserConfigurationException | SAXException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
'''
I get this error:
com.github.koraktor.steamcondenser.exceptions.SteamCondenserException: XML data could not be parsed.
    at com.github.koraktor.steamcondenser.steam.community.SteamId.fetchData(SteamId.java:381)
    at com.github.koraktor.steamcondenser.steam.community.SteamId.<init>(SteamId.java:295)
    at com.github.koraktor.steamcondenser.steam.community.SteamId.create(SteamId.java:233)
    at com.github.koraktor.steamcondenser.steam.community.SteamId.create(SteamId.java:139)
    at mika.tf2noobfinder.NoobFinder.main(NoobFinder.java:29)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: http://steamcommunity.com/id/market03?xml=1
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
    at com.github.koraktor.steamcondenser.steam.community.XMLData.<init>(XMLData.java:67)
    at com.github.koraktor.steamcondenser.steam.community.SteamId.fetchData(SteamId.java:326)
    ... 4 more

**Comment by ghost** [comment]
Now I'm getting a different error
[Fatal Error] loose.dtd:31:3: The declaration for the entity "HTML.Version" must end with '>'.
org.xml.sax.SAXParseExceptionpublicId: -//W3C//DTD HTML 4.01 Transitional//EN; systemId: http://www.w3.org/TR/html4/loose.dtd; lineNumber: 31; columnNumber: 3; The declaration for the entity "HTML.Version" must end with '>'.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
    at com.github.koraktor.steamcondenser.steam.community.XMLData.<init>(XMLData.java:67)
    at mika.tf2noobfinder.NoobFinder.isF2P(NoobFinder.java:49)
    at mika.tf2noobfinder.NoobFinder.main(NoobFinder.java:29)

**Comment by JohnAmican** [comment]
I think this is a fault of the Steam Community API, and not steam-condenser. Most of the time when I try to look at some of my community pages in XML format I get a 503: http://steamcommunity.com/id/jflash/games?tab=all&xml=1

For now I've just been retrying a bunch until it works. I'm hoping Steam fixes this.

**Comment by koraktor** [comment]
JohnAmican is right, the errors are caused by Steam's API itself, so there's nothing we can do here.

**Comment by Yeggstry** [comment]
Is this something that could be handled with more detail in the XMLData class to provide some more detail to the end user? I was pondering something like a ServiceUnavailableException for the 503 that would make it easier to catch and retry the service call.

**Comment by koraktor** [comment]
Sounds like a good idea, but it shouldn't be coupled to tightly too HTTP status codes. At least for Java, we might need to rewrite some parts to make use of Apache HttpClient, so we can get more unified errors while using HTTP endpoints.

**Comment by Yeggstry** [comment]
Agreed, you don't want to miss any status codes that are important. Though I guess this would help with handling any 400 Bad Request that come from the Web API.

**Comment by koraktor** [comment]
Sure, what I mean is "don't have an exception class for each HTTP status". Instead I guess it's probably best to have one exception class like `WebApiException`, but for the XML interface.

**Comment by Yeggstry** [comment]
Agreed. Something that indicates that the exception is recoverable would be useful i.e. you _may_ get the expected output if you retry the same request.

I guess there aren't many situations other than the 503 where this would be useful, but at least it would allow the users of the API to write some retry code over these recoverable exceptions. At the moment you have to interrogate the message of the WebApiException cause to see if a 503 has occurred, which is not a reliable source compared to the status code.

**Comment by Yeggstry** [comment]
FYI, it appears that the community data is now being rate limited: http://steamcommunity.com/discussions/forum/7/846941710472857299/#c864956554619133939

If they provided that data in the Web API then they wouldn't have to rate limit it! :)
