### ISSUE TITLE
Having Errors

### ISSUE THREAD

**Issue by zerdo** [koraktor/steam-condenser#210]
Hi,

im getting errrors when using this code : 

``` php
require_once '/lib/steam-condenser.php';
$server = new SourceServer('173.199.110.137', 27015);
$server->initialize();
print_r($server->getPlayers());
```

Errors:

``````
Notice: Sending packet of type "A2S_INFO_Packet"... in /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/steam/sockets/SteamSocket.php on line 144 Warning: socket_send(): unable to write to socket [1]: Operation not permitted in /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/Socket.php on line 163 Fatal error: Uncaught exception 'SocketException' with message 'Operation not permitted (Code: 1)' in /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/Socket.php:165 Stack trace: #0 /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/steam/sockets/SteamSocket.php(146): Socket->send('????TSource Eng...') #1 /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/steam/servers/GameServer.php(365): SteamSocket->send(Object(A2S_INFO_Packet)) #2 /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/steam/servers/GameServer.php(395): GameServer->sendRequest(Object(A2S_INFO_Packet)) #3 /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/steam/servers/GameServer.php(249): GameServer->updatePing() #4 /var/www/vhosts/7/142975/webspace/httpdocs/website.com/serverlist.php(6): GameServer->initialize() #5 /var/www/vhosts/7/142975/webspace/httpdocs/website.com/indexnew.php(49): include('/var/www/vhosts...') #6 {main} thrown in /var/www/vhosts/7/142975/webspace/httpdocs/website.com/lib/Socket.php on line 165```
``````

**Comment by gallomimia** [comment]
Right. This is either you are not allowed to access sockets by your server administrator
or, you haven't pointed your library include correctly. Do I remember how to fix this? The location of the file pointed to at require_once is either one dir level too deep or too high. No? Probably wrong.

**Comment by zerdo** [comment]
Well i tryed this on my own pc and it worked, so i guess i dont have access, what kind of access do i have to ask them to give me? or do they need to open a port?

**Comment by gallomimia** [comment]
Access to opening outgoing sockets. They're sometimes blocked to prevent odd scripts or spam being sent. I had a problem like this and asked my host, but it turns out I had the includes pointed to the wrong directory.

**Comment by koraktor** [comment]
This definitely looks like a permission problem (most likely due to restrictions by your host).

**Comment by koraktor** [comment]
Closing this as invalid as long as there's no hint at a bug in Steam Condenser.
