### ISSUE TITLE
Source Master down?

### ISSUE THREAD

**Issue by awillinger** [koraktor/steam-condenser#220]
Hello,

I've been trying to get the latest version of Steam Condenser working in Java, with no Success.
The MasterServer Request simply times out..

My Code:

``` java
import java.net.InetSocketAddress;
import java.util.Vector;
import java.util.concurrent.TimeoutException;

import com.github.koraktor.steamcondenser.exceptions.SteamCondenserException;
import com.github.koraktor.steamcondenser.steam.servers.MasterServer;

public class FetchServer {
    public void fetch()
    {
        try
        {
            MasterServer master = new MasterServer(MasterServer.SOURCE_MASTER_SERVER);   
            Vector<InetSocketAddress> servers = master.getServers(MasterServer.REGION_ALL, "\\type\\d\\gamedir\\tf");

            int count = servers.size();

        }
        catch (SteamCondenserException e) 
        {
            e.printStackTrace();
        } 
        catch (TimeoutException e) 
        {
            e.printStackTrace();
        }
    }
}

```

Result:

```
Aug 19, 2013 9:13:22 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:25 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server hl2master.steampowered.com/208.64.200.39 timed out, retrying...
Aug 19, 2013 9:13:25 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:28 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server hl2master.steampowered.com/208.64.200.39 timed out, retrying...
Aug 19, 2013 9:13:28 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:30 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server failed, retrying hl2master.steampowered.com/208.64.200.52...
Aug 19, 2013 9:13:30 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:33 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server hl2master.steampowered.com/208.64.200.52 timed out, retrying...
Aug 19, 2013 9:13:33 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:35 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server hl2master.steampowered.com/208.64.200.52 timed out, retrying...
Aug 19, 2013 9:13:35 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:38 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server failed, retrying hl2master.steampowered.com/208.64.200.65...
Aug 19, 2013 9:13:38 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:40 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server hl2master.steampowered.com/208.64.200.65 timed out, retrying...
Aug 19, 2013 9:13:40 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
Aug 19, 2013 9:13:43 PM com.github.koraktor.steamcondenser.steam.servers.MasterServer getServers
INFO: Request to master server hl2master.steampowered.com/208.64.200.65 timed out, retrying...
Aug 19, 2013 9:13:43 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2M_GET_SERVERS_BATCH2_Paket"
java.util.concurrent.TimeoutException
    at com.github.koraktor.steamcondenser.steam.sockets.SteamSocket.receivePacket(SteamSocket.java:112)
    at com.github.koraktor.steamcondenser.steam.sockets.MasterServerSocket.getReply(MasterServerSocket.java:49)
    at com.github.koraktor.steamcondenser.steam.servers.MasterServer.getServers(MasterServer.java:249)
    at com.github.koraktor.steamcondenser.steam.servers.MasterServer.getServers(MasterServer.java:196)
...

Did Valve change something again?
```

**Comment by koraktor** [comment]
Same for me. :zap:

**Comment by koraktor** [comment]
Ok, seems like a small, unexpected downtime on Valve's end. At least the server at 208.64.200.39 is responding right now.
