### ISSUE TITLE
java.net.SocketTimeoutException when using rconAuth()

### ISSUE THREAD

**Issue by realbucksavage** [koraktor/steam-condenser#292]
Hello.

I am using SteamCondenser v1.3.9.

I tried the following code

```
SourceServer server = new SourceServer("192.168.1.4", 
server.initSocket();
server.rconAuth("abcd");
```

Which threw a SocketTimeoutException.

The full stack trace is:- 
`com.github.koraktor.steamcondenser.exceptions.SteamCondenserException
    at com.github.koraktor.steamcondenser.steam.sockets.RCONSocket.send(RCONSocket.java:79)
    at com.github.koraktor.steamcondenser.steam.servers.SourceServer.rconAuth(SourceServer.java:147)
    at org.snh.gamequery.test.GameQueryTest.main(GameQueryTest.java:21)
Caused by: java.net.SocketTimeoutException
    at sun.nio.ch.SocketAdaptor.connect(Unknown Source)
    at com.github.koraktor.steamcondenser.steam.sockets.RCONSocket.send(RCONSocket.java:72)
    ... 2 more
`

What is the error on my side?

**Comment by koraktor** [comment]
What game is this?

**Comment by realbucksavage** [comment]
Counter Strike 1.6

**Comment by koraktor** [comment]
CS 1.6 is a GoldSrc (Half-Life 1) game. Please use `GoldSrcServer`.
