### ISSUE TITLE
Unknown packet with header 4 received

### ISSUE THREAD

**Issue by kawaijoe** [koraktor/steam-condenser#294]
Hi,

I'm trying to issue some basic RCON commands to a rust server. I managed to establish a connection with the server. However, I kept getting an error when I try to execute an RCON command.

This is the piece of code I have used. (IP address, Port and Passwords have been replaced for obvious reasons.)  

```
 SourceServer server;
        try {
            server = new SourceServer("IP ADDRESS", PORT);
            server.rconAuth("PASSWORD");
           System.out.println(server.rconExec("status"));
        } catch(RCONNoAuthException e) {
            System.err.println("Could not authenticate with the game server.");
        } catch (SteamCondenserException e) {
            e.printStackTrace();
        } catch (TimeoutException e) {
            e.printStackTrace();
        }
```

Console output

```
Mar 09, 2016 3:18:24 PM com.github.koraktor.steamcondenser.steam.sockets.RCONSocket getReply
INFO: Received packet of type "class com.github.koraktor.steamcondenser.steam.packets.rcon.RCONExecResponsePacket".
Mar 09, 2016 3:18:24 PM com.github.koraktor.steamcondenser.steam.sockets.RCONSocket getReply
INFO: Received packet of type "class com.github.koraktor.steamcondenser.steam.packets.rcon.RCONAuthResponse".
com.github.koraktor.steamcondenser.exceptions.PacketFormatException: Unknown packet with header 4 received.
    at com.github.koraktor.steamcondenser.steam.packets.rcon.RCONPacketFactory.getPacketFromData(RCONPacketFactory.java:46)
    at com.github.koraktor.steamcondenser.steam.sockets.RCONSocket.getReply(RCONSocket.java:123)
    at com.github.koraktor.steamcondenser.steam.servers.SourceServer.rconExec(SourceServer.java:182)
    at com.teamkarbon.App.main(App.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by koraktor** [comment]
Rust uses a modified RCON protocol and is not fully supported. See #252.
