### ISSUE TITLE
Use of GameInventory.create on certain games results in a 404 error

### ISSUE THREAD

**Issue by Tsa6** [koraktor/steam-condenser#302]
Specifically, I found Unturned and Don't Starve Together to produce a 404 error, though I'm sure this is true of more games as well.  The output below is from a call to my own account's Don't Starve Together inventory, which is public and has items, though it affects other inventories as well.  The api key I'm using does work for other games.  

> Console Output
`Nov 06, 2016 11:39:47 AM com.github.koraktor.steamcondenser.steam.community.WebApi load
INFO: Querying Steam Web API: https://api.steampowered.com/IEconItems_322330/GetPlayerItems/v0001/?format=json&key=SECRET&SteamID=76561198065248668
Exception in thread "main" com.github.koraktor.steamcondenser.exceptions.WebApiException: The Web API request has failed due to an HTTP error: Not Found (status code: 404).
	at com.github.koraktor.steamcondenser.steam.community.WebApi.load(WebApi.java:308)
	at com.github.koraktor.steamcondenser.steam.community.WebApi.getJSON(WebApi.java:144)
	at com.github.koraktor.steamcondenser.steam.community.WebApi.getJSONData(WebApi.java:200)
	at com.github.koraktor.steamcondenser.steam.community.GameInventory.fetch(GameInventory.java:203)
	at com.github.koraktor.steamcondenser.steam.community.GameInventory.<init>(GameInventory.java:188)
	at com.github.koraktor.steamcondenser.steam.community.GameInventory.create(GameInventory.java:138)
	at com.github.koraktor.steamcondenser.steam.community.GameInventory.create(GameInventory.java:72)
...`

**Comment by koraktor** [comment]
Steam’s Web API doesn’t support many games when it comes to inventories. Valve seems to have stopped development of this part of the API all together.

There’s an unsupported way using Steam’s internal API used on the web, inside Steam itself and the mobile apps. This hasn’t been integrated into Steam Condenser, though. (But I'm using it inside my own iOS app Suitcase.)
