### ISSUE TITLE
TimeoutException PHP

### ISSUE THREAD

**Issue by csprance** [koraktor/steam-condenser#305]
Everything was working fine for about the last year and then I started getting these all the time

Error:
```
PHP Fatal error:  Uncaught exception 'TimeoutException' with message 'The operation timed out.' in /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/sockets/SteamSocket.php:108
Stack trace:
#0 /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/sockets/SourceSocket.php(36): SteamSocket->receivePacket(1400)
#1 /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/servers/GameServer.php(260): SourceSocket->getReply()
#2 /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/servers/GameServer.php(302): GameServer->getReply()
#3 /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/servers/GameServer.php(472): GameServer->handleResponseForRequest(1)
#4 /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/servers/GameServer.php(235): GameServer->updateServerInfo()
#5 /var/www/miscreatedgam in /var/www/miscreatedgame.com.servers/public_html/api/vendor/koraktor/steam-condenser/lib/steam/sockets/SteamSocket.php on line 108
```

Here is my php code:
```php
<?php
// Return JSON
header('Content-Type: application/json');
// Turn off Error Reporting
error_reporting(0);


// Cache
require_once 'vendor/autoload.php';
$longcache = new Gilbitron\Util\SimpleCache();
$longcache->cache_path = 'cache/';
$longcache->cache_time = 3600;

// Steam Query
require 'steam-condenser-php-1.3.10/lib/steam-condenser.php';
$master = SourceServer::getMaster();
$servers = $master->getServers(MasterServer::REGION_ALL, '\appid\299740', true);


// Init the array we return
$serversWrapArray = Array();

// Find out if we have any cached date
if ($json = $longcache->get_cache('servers')) {

  //if it exists sweet! Echo that shit out!
  echo $json;

} else {
  // Otherwise go and get it all and then save it
  foreach ($servers as $key => $value) {
    $serversInfoArray = Array();
    $ip = $value[0];
    $port = $value[1];
    // Create instance of SourceServer using IP info collected from
    $server = new SourceServer($ip, $port);
    $serverInfo = $server->getServerInfo();
    // Server Name
    // Official Miscreated | TrinityGames.com USFL1
    $serverRetArray[0] = $serverInfo['serverName'];
    // Map Name
    // islands
    $serverRetArray[1] = $serverInfo['mapName'];
    // Number of Players
    // 13
    $tempvar = explode(';', $serverInfo['serverTags']);
    $numval = intval($tempvar[1]);
    $serverRetArray[2] = $numval;
    // Max Number of Players
    // 32
    $serverRetArray[3] = intval($serverInfo['maxPlayers']);
    // Time Of Day
    // 05:50
    $tempvar = explode(';', $serverInfo['serverTags']);
    $serverRetArray[4] = $tempvar[0];

    // Server Ip
    $serverRetArray[5] = $ip;
    // port
    $serverRetArray[6] = $port;
    // Server Version Info
    $serverRetArray[7] = $serverInfo['gameDesc'];

    array_push($serversWrapArray, $serverRetArray);
  }

  // convert to json
  $json = json_encode($serversWrapArray, JSON_NUMERIC_CHECK);

  // Spit it out
  echo $json;

  // set the cached data here. We may need to do some checking on some of these to exclude them
  $longcache->set_cache('servers', $json);

}

```

I've been looking around and I've adjusted the max_retries = 5 for the server itself as mentioned in another issue on the Google Group, but none of that seems to be solving anything.

Did Valve the protocol change recently? what happened that suddenly nothing works anymore?

**Comment by koraktor** [comment]
Does this happen for all servers? Did you try a single server with a known IP and port?

**Comment by csprance** [comment]
It works on single servers if the ip is known. I use both methods of querying the master server and then drilling down to each server individually.

**Comment by koraktor** [comment]
Oh, the solution is pretty easy when looking at your code. I answered from my phone, so I did not really look at it first.

You have to catch `TimeoutException`s inside your loop, because there will always be some servers that won’t answer your request, but still be listed on the master server.

```php
foreach ($servers as $key => $value) {
  $serversInfoArray = Array();
  $ip = $value[0];
  $port = $value[1];
  // Create instance of SourceServer using IP info collected from
  try {
    $server = new SourceServer($ip, $port);
    $serverInfo = $server->getServerInfo();
    // Server Name
    // Official Miscreated | TrinityGames.com USFL1
    $serverRetArray[0] = $serverInfo['serverName'];
    // Map Name
    // islands
    $serverRetArray[1] = $serverInfo['mapName'];
    // Number of Players
    // 13
    $tempvar = explode(';', $serverInfo['serverTags']);
    $numval = intval($tempvar[1]);
    $serverRetArray[2] = $numval;
    // Max Number of Players
    // 32
    $serverRetArray[3] = intval($serverInfo['maxPlayers']);
    // Time Of Day
    // 05:50
    $tempvar = explode(';', $serverInfo['serverTags']);
    $serverRetArray[4] = $tempvar[0];

    // Server Ip
    $serverRetArray[5] = $ip;
    // port
    $serverRetArray[6] = $port;
    // Server Version Info
    $serverRetArray[7] = $serverInfo['gameDesc'];

    array_push($serversWrapArray, $serverRetArray);
  } catch (TimeoutException $e) {
    // This server did not respond.
  }
}
```

**Comment by hayden-t** [comment]
thank you for this! i think it should be mentioned in the readme or examples somewhere, as otherwise its a fatal error, that breaks your whole script, otherwise you can just put a continue in the catch part and loop will finish.

**Comment by hayden-t** [comment]
also the timeout length can be changed.
