### ISSUE TITLE
CSGO Server sending back RCONGoldSrcResponsePacket

### ISSUE THREAD

**Issue by BrutalCSkakan** [koraktor/steam-condenser#326]
Hello!
When calling getPlayers() we send the regular A2S_PLAYER_Packet, and we expect S2A_PLAYER_Packet back from the server.

But I get RCONGoldSrcResponsePacket back instead. Has something changed that causes this behaviour? Is there anything that I can set up on the server to retrieve the correct payload?

> 2019-12-07 09:46:51.075  INFO 13692 --- [   scheduling-1] s.servers.sockets.SourceSocket           : Received reply of type "RCONGoldSrcResponsePacket"
2019-12-07 09:46:51.112  INFO 13692 --- [   scheduling-1] s.servers.sockets.QuerySocket            : Sending data packet of type "A2S_PLAYER_Packet"
steamcondenser.exceptions.SteamCondenserException: Response of type class steamcondenser.servers.packets.rcon.RCONGoldSrcResponsePacket cannot be handled by this method.
	at steamcondenser.servers.GameServer.handleResponseForRequest(GameServer.java:343)
	at steamcondenser.servers.GameServer.handleResponseForRequest(GameServer.java:288)
	at steamcondenser.servers.GameServer.updatePlayers(GameServer.java:531)
	at steamcondenser.servers.GameServer.getPlayers(GameServer.java:207)

**Comment by koraktor** [comment]
This is probably caused by CS:GO limiting the output by default.
See [this issue comment][1] on how to enable the old behavior.

 [1]: https://github.com/koraktor/steam-condenser/issues/275#issuecomment-113069411

**Comment by BrutalCSkakan** [comment]
That's unfortunately already set to 2..

**Comment by koraktor** [comment]
I’ll reply in this issue as the other one is already closed.

> And what would you suggest when the host_players_show is set to 2, but still get the RCONGoldSrcResponsePacket when sending the A2S_PLAYER_Packet?

To be honest I have no idea. Can you share the server IP so I can test directly?
