### ISSUE TITLE
error in steamid create (); in java

### ISSUE THREAD

**Issue by Ruan-Silva-Git** [koraktor/steam-condenser#332]
[Fatal Error] demomenz?xml=1:1:1: Premature end of file.
com.github.koraktor.steamcondenser.exceptions.SteamCondenserException: XML data could not be parsed: Premature end of file.
	at com.github.koraktor.steamcondenser.steam.community.XMLData.<init>(XMLData.java:70)
	at com.github.koraktor.steamcondenser.steam.community.SteamId.fetchData(SteamId.java:330)
	at com.github.koraktor.steamcondenser.steam.community.SteamId.<init>(SteamId.java:299)
	at com.github.koraktor.steamcondenser.steam.community.SteamId.create(SteamId.java:237)
	at com.github.koraktor.steamcondenser.steam.community.SteamId.create(SteamId.java:175)
	at me.ruan.sla2.main(sla2.java:38)
Caused by: org.xml.sax.SAXParseException; systemId: http://steamcommunity.com/id/demomenz?xml=1; lineNumber: 1; columnNumber: 1; Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:178)
	at com.github.koraktor.steamcondenser.steam.community.XMLData.<init>(XMLData.java:68)
	... 5 more

**Comment by koraktor** [comment]
Is this still a problem? The XML returned by that URL looks valid, although it's redirecting to HTTPS.

**Comment by fross72** [comment]
I'm having the same issue
